-- Both menus as transcribed from the printed menus ("main menu.jpg", "noir menu.jpg"). Staff edit them from here on.
UPDATE "branches" SET "menu_notes" = '[]'::jsonb WHERE "id" = 'main';
--> statement-breakpoint
UPDATE "branches" SET "menu_notes" = '["All espresso drinks come with 2 shots of espresso."]'::jsonb WHERE "id" = 'noir';
--> statement-breakpoint
INSERT INTO "menu_categories" ("branch_id", "slug", "title", "note", "sizes", "kind", "sort") VALUES
  ('main', 'caffeinated', 'Caffeinated', 'Hot or iced', '["Tall","Medium","Large"]'::jsonb, 'drink', 1),
  ('main', 'signature', 'Signature', 'Upsize +₱15', NULL, 'drink', 2),
  ('main', 'affogato', 'Gelato Affogato', NULL, NULL, 'drink', 3),
  ('main', 'non-caffeinated', 'Non Caffeinated', 'Upsize +₱15', NULL, 'drink', 4),
  ('main', 'refreshers', 'Refreshers', 'Upsize +₱15', NULL, 'drink', 5),
  ('main', 'tea', 'Tea Series', 'Upsize +₱15', NULL, 'drink', 6),
  ('main', 'yogurt', 'Yogurt Series', NULL, NULL, 'drink', 7),
  ('main', 'rice-meals', 'Rice Meals', NULL, NULL, 'food', 8),
  ('main', 'finger-snacks', 'Finger Snacks', '+₱25 per sauce', NULL, 'food', 9),
  ('noir', 'caffeinated', 'Caffeinated Drinks', NULL, '["16 oz","22 oz","Hot"]'::jsonb, 'drink', 1),
  ('noir', 'specialty', 'Specialty Drinks', NULL, '["16 oz","22 oz"]'::jsonb, 'drink', 2),
  ('noir', 'milk', 'Milk Series', '16 oz · upsize +₱15', NULL, 'drink', 3),
  ('noir', 'milk-tea', 'Milk Teas & Matcha', '16 oz · upsize +₱15', NULL, 'drink', 4),
  ('noir', 'refreshers', 'Refreshers', '16 oz · upsize +₱15', NULL, 'drink', 5),
  ('noir', 'yogurt', 'Yogurt-based Refreshers', '16 oz', NULL, 'drink', 6);
--> statement-breakpoint
INSERT INTO "menu_items" ("category_id", "name", "note", "prices", "star", "home_pick", "sort")
SELECT c."id", v."name", v."note", v."prices"::jsonb, v."star", v."home_pick", v."sort"
FROM (VALUES
  ('main', 'caffeinated', 'Americano', NULL, '[90,100,115]', false, NULL, 1),
  ('main', 'caffeinated', 'White Mocha', NULL, '[120,130,145]', false, NULL, 2),
  ('main', 'caffeinated', 'Spanish Latte', NULL, '[115,125,140]', false, 1, 3),
  ('main', 'caffeinated', 'Sea Salt Spanish Latte', NULL, '[120,130,145]', false, NULL, 4),
  ('main', 'caffeinated', 'Flavored Macchiato', 'Salted caramel, caramel or hazelnut', '[120,130,145]', false, NULL, 5),
  ('main', 'caffeinated', 'Café Mocha', NULL, '[125,135,150]', false, NULL, 6),
  ('main', 'caffeinated', 'Biscoff Latte', NULL, '[125,135,150]', false, 4, 7),
  ('main', 'caffeinated', 'Matcha Latte', NULL, '[115,125,140]', false, NULL, 8),
  ('main', 'signature', 'Iced Mont Blanc Espresso', NULL, '[160]', false, NULL, 1),
  ('main', 'signature', 'Iced Irish Cream Coffee', NULL, '[150]', false, NULL, 2),
  ('main', 'signature', 'Dark Hazelnut Cold Foam', NULL, '[165]', false, NULL, 3),
  ('main', 'signature', 'Ilonggo Brew Muscovado', 'Iced shaken espresso', '[125]', false, 3, 4),
  ('main', 'signature', 'Brown Sugar', 'Iced shaken espresso', '[120]', false, NULL, 5),
  ('main', 'signature', 'Barista Drink', 'Hot or iced', '[135]', false, NULL, 6),
  ('main', 'signature', 'Peanut Butter Cloud', 'Hot or iced', '[175]', false, 2, 7),
  ('main', 'affogato', 'Vanilla Cream', NULL, '[110]', false, NULL, 1),
  ('main', 'affogato', 'Caramel', NULL, '[115]', false, NULL, 2),
  ('main', 'affogato', 'Cookies and Cream', NULL, '[120]', false, NULL, 3),
  ('main', 'affogato', 'Dark Chocolate', NULL, '[120]', false, NULL, 4),
  ('main', 'affogato', 'Salted Caramel', NULL, '[115]', false, NULL, 5),
  ('main', 'affogato', 'White Chocolate', NULL, '[115]', false, NULL, 6),
  ('main', 'affogato', 'Biscoff', NULL, '[145]', false, NULL, 7),
  ('main', 'non-caffeinated', 'Hazelnut Chocolate', 'Hot or iced', '[120]', false, NULL, 1),
  ('main', 'non-caffeinated', 'White Chocolate Milk', 'Hot or iced', '[125]', false, NULL, 2),
  ('main', 'non-caffeinated', 'Signature Chocolate Milk', 'Hot or iced', '[110]', false, NULL, 3),
  ('main', 'non-caffeinated', 'Sakura Milk', NULL, '[110]', false, NULL, 4),
  ('main', 'non-caffeinated', 'Ube Milk Macapuno', NULL, '[130]', false, NULL, 5),
  ('main', 'refreshers', 'Iced Tea with Grenadine', 'Apple, lemon or cranberry', '[90]', false, NULL, 1),
  ('main', 'refreshers', 'Blood Moon', NULL, '[115]', false, NULL, 2),
  ('main', 'refreshers', 'Sunrise', NULL, '[115]', false, NULL, 3),
  ('main', 'refreshers', 'Blueberry Spritz', NULL, '[100]', false, NULL, 4),
  ('main', 'refreshers', 'Simba', NULL, '[115]', false, NULL, 5),
  ('main', 'refreshers', 'Ocean Breeze', NULL, '[125]', false, NULL, 6),
  ('main', 'tea', 'Thai Tea Latte', NULL, '[130]', false, NULL, 1),
  ('main', 'tea', 'Black Tea Latte', NULL, '[125]', false, NULL, 2),
  ('main', 'yogurt', 'Strawberry', NULL, '[120]', false, NULL, 1),
  ('main', 'yogurt', 'Blueberry', NULL, '[120]', false, NULL, 2),
  ('main', 'yogurt', 'Mango', NULL, '[120]', false, NULL, 3),
  ('main', 'rice-meals', 'Burgersteak', NULL, '[185]', false, 1, 1),
  ('main', 'rice-meals', 'German Franks Sausage', NULL, '[200]', false, NULL, 2),
  ('main', 'rice-meals', 'Chicken Chipoleta', NULL, '[200]', false, NULL, 3),
  ('main', 'rice-meals', 'Hungarian Sausage', NULL, '[200]', false, NULL, 4),
  ('main', 'finger-snacks', 'French Fries', NULL, '[65]', false, NULL, 1),
  ('main', 'finger-snacks', 'Chicken Nuggets', '6 pcs', '[115]', false, NULL, 2),
  ('main', 'finger-snacks', 'Chicken Nuggets with Fries', NULL, '[170]', false, 2, 3),
  ('main', 'finger-snacks', 'Nachos', NULL, '[115]', false, NULL, 4),
  ('main', 'finger-snacks', 'Nachos with Fries', NULL, '[165]', false, 3, 5),
  ('main', 'finger-snacks', 'Onion Rings', NULL, '[100]', false, NULL, 6),
  ('main', 'finger-snacks', 'Mozza Sticks', NULL, '[155]', false, 4, 7),
  ('noir', 'caffeinated', 'Americano', NULL, '[95,105,105]', false, NULL, 1),
  ('noir', 'caffeinated', 'Café Latte', NULL, '[115,125,125]', false, NULL, 2),
  ('noir', 'caffeinated', 'Café Mocha', NULL, '[120,130,130]', false, NULL, 3),
  ('noir', 'caffeinated', 'White Mocha', NULL, '[120,130,130]', false, NULL, 4),
  ('noir', 'caffeinated', 'Flavored Macchiato', 'Salted caramel, caramel or hazelnut', '[120,130,130]', false, NULL, 5),
  ('noir', 'caffeinated', 'Spanish Latte', NULL, '[125,135,135]', true, NULL, 6),
  ('noir', 'caffeinated', 'Biscoff Latte', NULL, '[130,140,140]', true, NULL, 7),
  ('noir', 'caffeinated', 'Sea Salt Latte', NULL, '[130,140,null]', false, NULL, 8),
  ('noir', 'specialty', 'Barista Drink', NULL, '[130,145]', true, NULL, 1),
  ('noir', 'specialty', 'Ilonggo Brew Muscovado', 'Iced shaken espresso', '[125,140]', true, NULL, 2),
  ('noir', 'specialty', 'Irish Cream', NULL, '[140,155]', false, NULL, 3),
  ('noir', 'specialty', 'Mont Blanc', 'Orange + espresso', '[150,165]', false, NULL, 4),
  ('noir', 'specialty', 'Dark Hazelnut Cloud', 'Americano-based', '[155,170]', false, NULL, 5),
  ('noir', 'specialty', 'Peanut Butter Cloud Latte', NULL, '[155,170]', true, NULL, 6),
  ('noir', 'milk', 'Chocolate Milk', NULL, '[110]', false, NULL, 1),
  ('noir', 'milk', 'Sakura Milk', NULL, '[110]', false, NULL, 2),
  ('noir', 'milk', 'White Chocolate Milk', NULL, '[120]', false, NULL, 3),
  ('noir', 'milk', 'Hazelnut Chocolate', NULL, '[120]', false, NULL, 4),
  ('noir', 'milk', 'Ube Milk Macapuno', NULL, '[120]', true, NULL, 5),
  ('noir', 'milk-tea', 'Thai Milk Tea', 'ChaTraMue', '[115]', false, NULL, 1),
  ('noir', 'milk-tea', 'Black Tea Latte', NULL, '[115]', false, NULL, 2),
  ('noir', 'milk-tea', 'Matcha Latte', NULL, '[125]', true, NULL, 3),
  ('noir', 'milk-tea', 'Strawberry Matcha', NULL, '[150]', false, NULL, 4),
  ('noir', 'refreshers', 'Blueberry Spritz', NULL, '[100]', true, NULL, 1),
  ('noir', 'refreshers', 'Sunrise', 'Orange', '[105]', false, NULL, 2),
  ('noir', 'refreshers', 'Bloodmoon', 'Pineapple', '[105]', false, NULL, 3),
  ('noir', 'refreshers', 'Iced Tea with Grenadine', NULL, '[90]', false, NULL, 4),
  ('noir', 'yogurt', 'Strawberry', NULL, '[110]', false, NULL, 1),
  ('noir', 'yogurt', 'Blueberry', NULL, '[110]', false, NULL, 2)
) AS v("branch", "slug", "name", "note", "prices", "star", "home_pick", "sort")
JOIN "menu_categories" c ON c."branch_id" = v."branch" AND c."slug" = v."slug";
--> statement-breakpoint
INSERT INTO "menu_addons" ("branch_id", "name", "price", "sort") VALUES
  ('main', 'Extra shot', 25, 1),
  ('main', 'Double shot', 35, 2),
  ('main', 'Add sinkers', 25, 3),
  ('noir', 'Coconut jelly', 15, 1),
  ('noir', 'Syrup', 20, 2),
  ('noir', 'Breve', 25, 3),
  ('noir', 'Extra espresso shot', 25, 4),
  ('noir', 'Double shot', 40, 5),
  ('noir', 'Sub oat milk', 40, 6);
